// Copyright © 2024 Rangeproof Pty Ltd. All rights reserved.
// This file is automatically generated and maintained, do not manually edit it.
//
// stringlint:disable

public enum Constants {
    static let token_name_short: String = "SENT"
    static let token_name_long: String = "Session Token"
    static let token_name_long_plural: String = "Session Tokens"
    static let ethereum: String = "Ethereum"
    static let network_name: String = "Session Network"
    static let app_name: String = "Session"
    static let arbitrum: String = "Arbitrum"
    static let arbiscan: String = "Arbiscan"
}
