name: Check for Crowdin Updates

on:
  push

jobs:
  fetch_convert_and_diff_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Content
        uses: actions/checkout@v3
        with:
          ref: 'dev'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Download and Convert Translations
        env:
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
        run: |
          python Scripts/download_and_convert_translations.py \
            "$CROWDIN_API_TOKEN" \                    # api_token
            618696 \                                  # project_id
            "./raw_translations" \                    # download_directory
            "./Session/Meta" \                        # output_directory
            "./Scripts/xliff_to_string_catalog.py" \  # conversion_script
            --single-output \
            --skip-untranslated-strings
          rm -rf "./raw_translations"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Update translations from Crowdin
          body: This PR includes the latest translations from Crowdin
          commit-message: [Automated] Update translations from Crowdin
          branch: feature/update-translations
          delete-branch: true
