name: Check for Crowdin Updates

on:
  push

jobs:
  fetch_convert_and_diff_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Content
        uses: actions/checkout@v4
        with:
          path: 'repo'
          ref: 'dev'
      - name: Checkout LibSession
        uses: actions/checkout@v4
        with:
          repository: 'mpretty-cyro/libsession-util'
          path: 'libsession'
          ref: 'feature/shared-scripts'
      - name: Checkout LibSession
        uses: actions/checkout@v4
        with:
          repository: 'mpretty-cyro/session-android'
          path: 'android'
          ref: 'dev'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: 'pip' # caching pip dependencies
      - name: Install Dependencies
        run: |
          pip install -r ${{ github.workspace }}/libsession/utils/shared-scripts/requirements.txt
      - name: Download and Convert Translations
        env:
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
        run: |
          python "${{ github.workspace }}/libsession/utils/shared-scripts/download_and_convert_translations.py" \
            "$CROWDIN_API_TOKEN" \
            618696 \
            407522 \
            36 \
            "${{ github.workspace }}/raw_translations" \
            "${{ github.workspace }}/repo/Session/Meta" \
            "${{ github.workspace }}/libsession/utils/shared-scripts/xliff_to_string_catalog.py" \
            "${{ github.workspace }}/repo/Session/Meta/Constants.swift" \
            "${{ github.workspace }}/libsession/utils/shared-scripts/static_strings_to_swift.py" \
            --single-output \
            --skip-untranslated-strings
          rm -rf "${{ github.workspace }}/raw_translations"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          path: 'repo'
          title: Update translations from Crowdin
          body: This PR includes the latest translations from Crowdin
          branch: feature/update-translations
          commit-message: "[Automated] Update translations from Crowdin"
          delete-branch: true
      - name: Create Pull Request Cross Repo
        uses: peter-evans/create-pull-request@v6
        with:
          path: 'android'
          token: ${{ secrets.CROWDIN_PR_TOKEN }}
          title: Update translations from Crowdin cross-repo
          body: This PR includes the latest translations from Crowdin cross-repo
          branch: feature/update-translations-cross-repo
          commit-message: "[Automated] Update translations from Crowdin cross-repo"
          delete-branch: true
 